name: Show Files on Push

on:
  workflow_dispatch:

jobs:
 hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list files
        run: ls -la